pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - base=master
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
  - name: automatically merge my (eikek) PRs on CI success
    conditions:
      - author=eikek
      - base=master
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
