sudo: false
language: scala
scala:
  - 2.12.11
  - 2.13.2

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier/cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION ";scalafmtCheckAll ;test"
